### ISSUE TITLE
Crux migrating to Maven Central

### ISSUE THREAD

**Issue by jarohen** [jacobobryant/biff#103]
Hey @jacobobryant - guess you've probably seen this on the Clojurians Slack but thought I'd raise an issue here just in case. 

A quick heads up that we're looking to migrate Crux over to Maven Central shortly - we've got a couple of non-Clojure modules coming soon, and would generally like to make Crux more accessible/appealing to folks outside of the Clojure community too. We've mirrored our Clojars dependencies onto Central, and have re-released 1.17.1 (currently as `1.17.1-rc1`) so that users can migrate without having to upgrade Crux.

Crux PRs here:
* https://github.com/juxt/crux/pull/1543
* https://github.com/juxt/crux/pull/1550

Could you let us know if this will cause you any issues, or whether there's anything we should do/avoid doing? Otherwise, if this works for you, I'm happy to raise a quick PR with the required changes.

Cheers,

James

**Comment by jacobobryant** [comment]
Sounds good, and shouldn't cause any problems. No need to do a PR; I've got some other small changes I need to make too so I can take care of that as well. (I'll include a notice about upgrading Crux too since current version is pre-1.17.0).

**Comment by jarohen** [comment]
Great, thanks :) on second thoughts, will leave this one open, feel free to close.

**Comment by jacobobryant** [comment]
Just released this.
