### ISSUE TITLE
Logging suppression

### ISSUE THREAD

**Issue by genmeblog** [jacobobryant/biff#114]
Hi there!

I really like the idea of this project (no JS! yay!) and I'll give it a try soon. Great job!

I want to raise one issue I see now regarding logging.

Logging system in Java brings two layers: facade and backend. Facades like `slf4j` or `tools.logging` provide only API, leaving decision about logging backend (service provider) to the end-user. That means that any library/framework should include facade API and shouldn't include any backend. End-users on their side should configure backend, logging level and method (print to console, append to a file or maybe database).
When the library author includes a logging backend (or logging configuration), it may interfere with user setup.

Saying this: I strongly recommend to remove `slf4j-nop` from the main deps. If you don't want to see `xtdb` logs ust set up your local environment.

Also, instead of printing with `println` consider use of https://github.com/clojure/tools.logging.

**Comment by jacobobryant** [comment]
I actually wasn't aware till just now that there were log messages I was missing out on--I just put the nop backend in to get rid of the no-providers-found warning :).

I'm thinking to put `slf4j-simple` in the template project's deps.edn (i.e. `example/deps.edn`, which is copied into new projects), replacing slf4j-nop in the main deps; does that sound reasonable? I'll take a look at tools.logging as well.

**Comment by jacobobryant** [comment]
Closed by 5b3354a6eea041427c8df1b858b572624ba27c40

**Comment by genmeblog** [comment]
Sounds reasonable! Thanks!
