### ISSUE TITLE
Write a blog post to illustrate different types of interactivity

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#120]
For example:
 - htmx
 - hyperscript
 - plain JS
 - drop-in JS components
 - at what point should you switch to React?

**Comment by rlhk** [comment]
Any comment on mixing html & React?

**Comment by jacobobryant** [comment]
I haven't done it myself, but it sounds like a reasonable step in between using drop-in JS components and going full React.

**Comment by jacobobryant** [comment]
Closing because I'm moving documentation issues to a personal todo list.
