### ISSUE TITLE
Problems loading database on M1 Mac

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#124]
Moving this here from an email conversation. @tbrooke has a Biff project which occasionally boots up with an empty DB:

> I am running locally (M1 Mac) It disappears on the ./task dev at startup - It will occasionally start with a blank database . One time after a couple of starts I got the database back (this makes me think it might not be reading the database as opposed to nuking it) - It did it again yesterday and I was unable to get it back. I have been starting and restarting a lot in order to try to duplicate it and it hasn't happened again - I have very little in the database so it is easy to fix. Below is my startup output for a successful start. I will save it when it does it again to see if there is a difference.

(I've elided the startup output since it looks pretty normal, same as for any Biff app.)

Next time it does happen, also save the XTDB disk contents (`tar -czvf xtdb.tar.gz storage/xtdb/`). I'd be interested to see if I can load the db on my own machine.

(cc @refset, curious if you've heard reports of anything similar?)

**Comment by refset** [comment]
Nope :/ this sounds new to me, unfortunately. Is this a 3x RocksDB config?

**Comment by tbrooke** [comment]
Initial Startup with empty DB: (Looks same as normal to me)

➜  mtzion git:(master) ✗ ./task dev

up to date, audited 97 packages in 7s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 366 packages in 1s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
WARNING: abs already refers to: #'clojure.core/abs in namespace: juxt.clojars-mirrors.encore.v3v9v2.taoensso.encore, being replaced by: #'juxt.clojars-mirrors.encore.v3v9v2.taoensso.encore/abs
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_config@1d9f2b96
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_random_default_secrets@5baf9daf
[main] WARN com.biffweb.impl.misc - :biff.middleware/cookie-secret is empty, using random value
[main] WARN com.biffweb.impl.misc - :biff/jwt-secret is empty, using random value
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_xt@4c588735
[main] WARN xtdb.cache - Could not open ConcurrentHashMap.table field - falling back to LRU caching. Use `--add-opens java.base/java.util.concurrent=ALL-UNNAMED` to use the second-chance cache.
[main] INFO xtdb.tx - Started tx-ingester
[main] INFO com.biffweb.impl.xtdb - Indexed #:xtdb.api{:tx-time #inst "2022-08-17T12:57:42.171-00:00", :tx-id 128}
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_tx_listener@66d96549
[main] INFO com.biffweb.impl.util - starting: com.biffweb.impl.util$use_when$fn__2047@5d386670
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_outer_default_middleware@6b26ed4
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_jetty@56abb0b7
[main] INFO org.eclipse.jetty.server.Server - jetty-10.0.7; built: 2021-10-06T19:34:02.766Z; git: da8a4553af9dd84080931fa0f8c678cd2d60f3d9; jvm 17.0.2+8-LTS
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2ba9378{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@7e0666e5{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@7a848abb{STARTING}[10.0.7,sto=0] @12171ms
[main] INFO com.biffweb.impl.misc - Jetty running on http://0.0.0.0:8080
[main] INFO com.biffweb.impl.util - starting: com.biffweb.impl.util$use_when$fn__2047@36c19047
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_chime@ce2af8d
[main] INFO com.biffweb.impl.util - starting: com.biffweb.impl.util$use_when$fn__2047@3ad6bf05
[main] INFO com.biffweb.impl.util - starting: com.biffweb$use_beholder@af43b0
[main] INFO com.biffweb.impl.util - System started.
[main] INFO com.platypub - Generating CSS...
[main] INFO com.platypub - CSS done
[main] INFO com.platypub - Go to http://localhost:8080

Done in 164ms.
nREPL server started on port 7888 on host localhost - nrepl://localhost:7888
[qtp2068203949-25] INFO com.biffweb.impl.middleware -   5ms 200 get  /
Click here to sign in as tombo@gmail.com: http://localhost:8080/auth/verify/eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4R0NNIn0.2z8oD28_OyUyYfBfPlPHDtMA05xv3Z5t.AnbjQYki30N1jv1A.brlpiuYfj2mdRRPBpW2t8nSXc1R8rUtCvvdEGtOLBpe3SbCFbkduC4G1Ill4Ox8OCtu1emXH1_W5RJz77qoXVKXK0ha7KdSTSjMTDCb0-qnSIfXV4s2jaXgyXbPuZtjZeTS_q8lV8vT5SCsCT42s-Pza9KRkE7kVkyv8IYV89GfBgcxmhiFBL2s.zG0Ip64IgDtxbFYStOITgA
[qtp2068203949-21] INFO com.biffweb.impl.middleware -  11ms 303 post /auth/send
[qtp2068203949-24] INFO com.biffweb.impl.middleware -   8ms 200 get  /auth/sent/
[qtp2068203949-26] INFO com.biffweb.impl.middleware -  84ms 303 get  /auth/verify/eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4R0NNIn0.2z8oD28_OyUyYfBfPlPHDtMA05xv3Z5t.AnbjQYki30N1jv1A.brlpiuYfj2mdRRPBpW2t8nSXc1R8rUtCvvdEGtOLBpe3SbCFbkduC4G1Ill4Ox8OCtu1emXH1_W5RJz77qoXVKXK0ha7KdSTSjMTDCb0-qnSIfXV4s2jaXgyXbPuZtjZeTS_q8lV8vT5SCsCT42s-Pza9KRkE7kVkyv8IYV89GfBgcxmhiFBL2s.zG0Ip64IgDtxbFYStOITgA
[qtp2068203949-24] INFO com.biffweb.impl.middleware -   8ms 303 get  /app
[qtp2068203949-26] INFO com.biffweb.impl.middleware -   4ms 200 get  /sites

**Comment by jacobobryant** [comment]
> Is this a 3x RocksDB config?

Yep, here's the config: https://github.com/jacobobryant/biff/blob/master/src/com/biffweb/impl/xtdb.clj#L24. I'm assuming `opts` is empty in this case.

@tbrooke I just started up platypub on my local machine using the xtdb.tar.gz file you emailed me, and everything looks fine. Can you go to repl.clj and eval this?

```clojure
(let [{:keys [biff/db] :as sys} (get-sys)]
    (q db
       '{:find (count doc)
         :where [[doc :xt/id]]})
    )
```

I get 37 as the result (i.e. there are 37 documents in the database). You can also eval this to see the user accounts:

```clojure
(let [{:keys [biff/db] :as sys} (get-sys)]
  (q db
     '{:find (pull user [*])
       :where [[user :user/email]]}))
```

I saw there were four accounts. Is it possible you're signing in to the wrong account, and that's why none of the data is showing up? I'm able to see this when I sign in to one of the accounts:

![image](https://user-images.githubusercontent.com/3696602/185256482-0b7ef687-2517-4c9d-b654-052b7ce4255d.png)

In addition, I see in your startup logs you have the following:

```
[main] INFO xtdb.tx - Started tx-ingester
[main] INFO com.biffweb.impl.xtdb - Indexed #:xtdb.api{:tx-time #inst "2022-08-17T12:57:42.171-00:00", :tx-id 128}
```

which means that XT has successfully indexed at least *some* transactions. So signing into the wrong account sounds like it may be the issue? However if you eval that first bit of code above and it returns an empty list (i.e. the query didn't find any documents in the database), then something funky is definitely going on.

**Comment by tbrooke** [comment]
Problem solved -- I have been changing my login without realizing it and it is coming in as a different account - I Logged in my old account tom@gmail.com and everything came back

**Comment by jacobobryant** [comment]
Excellent, glad to hear it.
