### ISSUE TITLE
Add :db/op :create

### ISSUE THREAD

**Issue by N-litened** [jacobobryant/biff#125]
I might be missing something (maybe there's a way to achieve the same with existing operation types somehow), but I think a :db/op `:create` would be a really useful thing — like `:put`, but will fail if older version with same ID exists, useful with :db/lookup. Like `:update`, but will fail when the old version **does** exist, and without "applying special vals".

This way, I can ensure that unique constraint is respected, and I don't "accidentally" overwrite something that was created earlier while thinking I've just created something new. Right now it's very cumbersome to check.

@jacobobryant, if you approve, I could draft a quick pull request.

**Comment by jacobobryant** [comment]
That seems reasonable, I'd be happy to merge a PR.

**Comment by N-litened** [comment]
Done, PR #130
