### ISSUE TITLE
:db/default attribute operation broken?

### ISSUE THREAD

**Issue by AndreasEdvardsson** [jacobobryant/biff#140]
Hi, 

Submitting a tx-doc with a [:db/default value] results in
```
ERROR com.biffweb.impl.middleware - Exception while handling request
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Keyword
```

The stack trace ends in `apply-special-vals`, and an inspection seems to reveal an inconsistency in the return value of the `:db/default` case.

https://github.com/jacobobryant/biff/blob/92a03324f98836d579878fc669eb702746551858/src/com/biffweb/impl/xtdb.clj#L182

**Comment by jacobobryant** [comment]
Thanks for fixing that! Very embarrassing :). I'll add a test for that and the other operations soon.
