### ISSUE TITLE
Repo for biffweb.com?

### ISSUE THREAD

**Issue by rlhk** [jacobobryant/biff#143]
Can't find the doc repo, so leave it here ...

https://biffweb.com/docs/get-started/new-project/
The dev command should be `bb dev` instead of `./task dev`, right?

**Comment by jacobobryant** [comment]
Yes, thanks for catching that.  `./task dev`  was previously the command before added in babashka. I'll fix that soon.

The repo is here by the way: https://github.com/jacobobryant/platypub-biffweb-theme
I'll probably add "edit this page" links to the docs at some point.
