### ISSUE TITLE
Better config naming for "main" branches

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#145]
@kyptin:

> Second, I have my git configured to use main as the default branch instead of master. I had to change the :tasks -> :biff.tasks/deploy-from key in my config.edn to "main:master" to get it to work. I'm not sure how much you care, but the name of the key doesn't really fit this use case. Perhaps renaming :biff.tasks/deploy-to to :biff.tasks/deploy-to-remote and :biff.tasks/deploy-from to :biff.tasks/deploy-branch? Or perhaps a new config key would be more clear to separate source branch and destination branch. That's a design decision that I'll leave in your capable hands.

**Comment by jacobobryant** [comment]
It is quite possible I botched the naming as I never actually tried pushing from a local repo that used `main` as the primary branch--I wonder if the irregularity has something to do with the server's repo being called `master` so the local + remote repos have different primary branch names. I'll look at this soon.

**Comment by kyptin** [comment]
Yeah that’s right. The remote side (on digital ocean) apparently still uses master as the default. And when you push, unless you specify different branch names on either side of a colon, git will assume you mean the same branch name locally and remotely.

BTW, I’m enjoying this whole process quite a bit. I’m learning about Digital Ocean (nifty!), Tailwind, Postmark, XTDB, etc. And Biff of course. Part of what I value here is seeing your highly refined set of technological opinions all connected together. Keep up the good work!

**Comment by jacobobryant** [comment]
🙂 thanks!

**Comment by jacobobryant** [comment]
This is fixed by [v0.5.6](https://github.com/jacobobryant/biff/releases/tag/v0.5.6) -- there's a new `:biff.tasks/deploy-cmd` option which supersedes `:biff.tasks/deploy-from` and `:biff.tasks/deploy-to`.
