### ISSUE TITLE
server-setup.sh fails on some machines due to missing dependencies

### ISSUE THREAD

**Issue by KarolisL** [jacobobryant/biff#146]
Some ubuntu installs are more minimal than others. The one I've encountered, lacked the following things:
- git
- ufw
- snapd

Since the missing dependency was revealed only once the script would execute the line containing the missing program, I kept running `rm -rf /home/app/ ; deluser app ; delgroup app` multiple times.

This could be solved by installing these dependencies as we install `default-jre`.

In the long run, it might make sense to make the script more resilient (in terms of error handling), so it would continue from a particular step it failed on.

**Comment by jacobobryant** [comment]
Thanks for the PR. I've developed the script against DigitalOcean's ubuntu install--it probably is more on the featureful side.

> In the long run, it might make sense to make the script more resilient (in terms of error handling), so it would continue from a particular step it failed on.

Agreed; just made an issue for this: #148
