### ISSUE TITLE
Remove comment in biffweb.clj

### ISSUE THREAD

**Issue by VictorVSa** [jacobobryant/biff#151]
I've noticed there is a dev comment with local paths at the bottom of the main biffweb.clj file.

Btw, I'm super new with clojure, it's quite hard for me to understand what I'm doing. I need a email/password authentication method, can I just ignore biff's authentication and user buddy-auth or am I going to have conflicts somewhere?

**Comment by jacobobryant** [comment]
Yep, I use that for updating the docs on the website. You can ignore it.

For authentication, it's totally fine to not use the provided auth plugin and supply your own. (and recommended, if you need something different like passwords.)
