### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by gdw2** [jacobobryant/biff#157]
```
$ bb -e "$(curl -s https://biffweb.com/new-project.clj)"
Invalid git branch: -e
```

I can workaround it by running:
```
$ bb -e "$(curl -s https://biffweb.com/new-project.clj)" master
```

Or by downloading new-project.clj and then running it without `master` on the end.

**Comment by gdw2** [comment]
```
$ bb --version
babashka v1.3.180
```

**Comment by jacobobryant** [comment]
Thanks for reporting this. Looks like there's been a recent breaking change/bug in babashka related to how it handles command line arguments. I've updated the new-project.clj script (https://github.com/jacobobryant/biff/commit/d0a3248c61b39ac9511bffb2ad52f310c08442d0) to work around it, so `bb -e "$(curl -s https://biffweb.com/new-project.clj)"` should work like normal now.
