### ISSUE TITLE
(Website) Hero section is fixed on mobile and obstructs view when scrolling

### ISSUE THREAD

**Issue by zakkor** [jacobobryant/biff#165]
![image](https://github.com/jacobobryant/biff/assets/6191421/a6c93fc6-4eb7-4d31-900c-a10629a8ae74)

**Comment by jacobobryant** [comment]
What browser + OS is this?

**Comment by jacobobryant** [comment]
I reproduced this on desktop safari. I've fixed it there. Let me know if the bug still happens on mobile.
