### ISSUE TITLE
[feature suggestion] biff libraries repository

### ISSUE THREAD

**Issue by efraimmgon** [jacobobryant/biff#171]
with the `plugin` var biff allows some pretty cool extensibility possiblities.

there is no place where biff users can use or share some common features, though, like https://reactnative.directory/ or simply https://github.com/jondot/awesome-react-native.

for example, one common feature for websites is oauth. if i'm a new biff user i have to come up with the logic by myself, even though i bet it has been done many times by other biff users.

why not have a page in the biff website, or in github, were users could share and use such common features?

i guess that even though many users aren't interested in contributing to the core library, many could contribute with something that already exists in their codebase.

(sorry for any spelling mistakes, not a native english speaker)

**Comment by jacobobryant** [comment]
This is what the content library is for: https://biffweb.com/docs/library/. E.g. someone's made a Biff authentication plugin already that I'm planning to add a link to on that page.

I expect that in most cases, a how-to guide for using an existing Clojure library with Biff will be best. E.g. if you're interested, you could create a new biff app, add some example oauth integrations with https://github.com/weavejester/ring-oauth2, then publish it to a public repo; then I could add a link to it on the content library.

**Comment by jacobobryant** [comment]
There is now also a Community section in the docs: https://biffweb.com/docs/community/
