### ISSUE TITLE
[Docs] Broken links on Should you use Biff article

### ISSUE THREAD

**Issue by jasalt** [jacobobryant/biff#180]
I noticed some broken links on https://biffweb.com/p/should-you-use-biff/ article.

After "These essays provide some additional background info that might help you further gauge if Biff is right for you:" the link is pointing to path `/sites/1227c578-6578-45da-9250-8941140e7fe1/preview?path=/p/philosophy-of-biff/` giving 404, while path is `/p/philosophy-of-biff/`.

Nice project, thank's!

**Comment by jacobobryant** [comment]
Thanks! Just fixed the links.
