### ISSUE TITLE
`install-tailwind` fetches the ARM binary on a x86 Mac

### ISSUE THREAD

**Issue by love-your-parens** [jacobobryant/biff#189]
Observed on an older, Intel-based macbook running Monterey. 

Perusing the task's code I see the following:

```clojure 
arch (case (System/getProperty "os.arch")
"amd64" "x64"
"arm64"
```

Meanwhile, evaluating `(System/getProperty "os.arch")` at the REPL, I get: `"x86_64"`

Unfortunately I have no idea whether this varies between recent versions of MacOS. I suppose simply adding an extra clause would sort this out without regressions.

**Comment by jacobobryant** [comment]
Thanks for the catch--I just pushed a commit that adds a clause for `"x86_64"`; can you confirm that it works? You can change your biff dependencies in `deps.edn` to `:git/sha "165b8aa", :git/tag "1.8.3"` and delete the `bin/tailwindcss` file if it's already been downloaded.

**Comment by love-your-parens** [comment]
It had me scratching my head for a moment since I hadn't noticed the dev dependency.  After updating:

```
Downloading the latest version of  tailwindcss-macos-x64 ...
```

And running the binary just to make extra sure:

```
tailwindcss v3.4.1
```

So it works just fine. Thank you very much for the quick fix!
