### ISSUE TITLE
Is it possible to keep assets files in modules?

### ISSUE THREAD

**Issue by vldmr-k** [jacobobryant/biff#191]
Hi, I'm interestin biff framework.
After reading docs, I would like to use module system for my app to extend it, but I don't understant how to keep custom js,css or iamges file in [modules](https://biffweb.com/docs/reference/architecture/).

Is it possible?

**Comment by jacobobryant** [comment]
Hi! For static assets, you don't need to expose them through the module system per se. You can put them somewhere under the `resources/public/` directory, then you can reference those files from your routes. e.g. if you put a file at `resources/public/images/hello.jpg`, you could then include `[:img {:src "/images/hello.jpg"}]` in one of your routes.
