### ISSUE TITLE
getting-started new-project doc error on windows

### ISSUE THREAD

**Issue by milelo** [jacobobryant/biff#222]
from [https://biffweb.com/docs/get-started/new-project/](https://biffweb.com/docs/get-started/new-project/)

On windows 11 PowerShell:
```
❯  clj -M -e '(load-string (slurp ""https://biffweb.com/new.clj""))'
Syntax error compiling at (REPL:1:14).
No such namespace: https:

Full report at:
C:\Users\mail\AppData\Local\Temp\clojure-366610206050372560.edn
```
This work fine:
```
❯ clj -M -e '(load-string (slurp "https://biffweb.com/new.clj"))'
```

**Comment by jacobobryant** [comment]
Interesting--I just tested this on Windows 10 again and I still get the exact reverse behavior. Maybe MS changed the way powershell escaping works in Windows 11? What version of clj are you on/how did you install it? (Not sure it would make any difference, just curious).

If the single-quote works on Windows 11, that sounds great to me--I'd love to only list one command on the create-a-project page anyway. I guess anyone using powershell (on Windows 10 at least?) will hopefully be familiar already with the need to add quotes to `clj` commands, so if they do run into problems maybe it won't be a big deal anyway. I'll go ahead and update the docs, and if someone opens another issue maybe I'll add a note or something.

**Comment by milelo** [comment]
Sorry, I must have missed a notification on this.
I'm using PowerShell 7.4.5.

**Comment by jacobobryant** [comment]
ah--just did a little googling on that; I didn't even realize there were two different versions of PowerShell. I've updated the website to say that the escaping _may_ be necessary; that oughtta cover all the bases:

```bash
clj -M -e '(load-string (slurp "https://biffweb.com/new.clj"))'

# In some versions of PowerShell, you may need to escape the quotes:
clj -M -e '(load-string (slurp ""https://biffweb.com/new.clj""))'
```
