### ISSUE TITLE
Old tags break SemVer, throwing dependency checkers

### ISSUE THREAD

**Issue by credmp** [jacobobryant/biff#230]
Old tags such as 20210630 throw dependency checker (ancient/antq). 

```
$ clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version "RELEASE"}}}' -M -m antq.core
| :file    | :name             | :current | :latest  |
|----------+-------------------+----------+----------|
| deps.edn | com.biffweb/biff  | v1.8.22  | 20210630 |
|          | com.biffweb/tasks | v1.8.22  | 20210630 |
```

Consider removing these tags to provide these checkers with correct information. The reason why this is important is that you might want to run outdated checks in CI.

**Comment by jacobobryant** [comment]
Sure--just deleted all the non-semver tags.
