### ISSUE TITLE
Replace Immutant

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#33]
Yogthos has a replacement that'll work with Sente:
https://www.reddit.com/r/Clojure/comments/h15jxh/biff_is_officially_released_web_framework/ftqh8pq/
https://github.com/luminus-framework/ring-undertow-adapter
https://github.com/ptaoussanis/sente/pull/372/files

**Comment by tbrooke** [comment]
@jacobobryant have you looked int [vertx](https://vertx.io/)  I have noticed that Juxt is using it some: [CMS Example](https://github.com/juxt/apex/blob/master/examples/cms/src/juxt/apex/examples/cms/vertx.clj). Not sure it would be a good fit but it seems like it would to me

**Comment by jacobobryant** [comment]
hadn't heard of it before--but main issue is sente support, which vertx doesn't have as far as I can tell.

we don't strictly have to use sente; vertx might be a good option if setting up web sockets with it some other way is easier than using yogthos's code above to get sente working with jetty. I've only ever used sente for web sockets myself.

**Comment by jacobobryant** [comment]
There was just a new Sente release, and Jetty support has been merged. So switching to Jetty should be pretty easy now.
