### ISSUE TITLE
Replace defderivations with odoyle-rum

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#57]
https://github.com/oakes/odoyle-rum. This could potentially replace biff.rum/defderivations, which would be great for performance (and correctness--see the last paragraph of https://jacobobryant.substack.com/p/a-macro-im-proud-of).

**Comment by rainbow-bamboo** [comment]
I'm definitely interested in exploring this. 

I used clara rules generate hiccup from data here https://rainbow-bamboo.github.io/coronavirus-charts/uberdoc.html#coronavirus-charts.sessions, so I feel like I've already ran into some of the challenges that motivated oakes to build odoyle-rum.

Outside of performance, I think that odoyle-rules/rum might be a good way to structure code for maintenance.

**Comment by jacobobryant** [comment]
If you want to take a stab at it that'd be great!

**Comment by jacobobryant** [comment]
New version of Biff uses HTMX instead of CLJS + React
