### ISSUE TITLE
Use Babashka to manage project files?

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#59]
With babashka, we could generate terraform config every time you call terraform. There would be no chance for out-of-date config files (which currently would happen if you updated `:biff/host` in `config/main.edn` without running `./task dev` afterwards).

However I want to keep the generation code in normal clojure files so they can be shared via regular dependency management (tools.deps). I need to look into babashka more to see what's possible.

**Comment by drewverlee** [comment]
> With babashka, we could generate terraform config every time you call terraform. 

Having the terraform alongside the deployment will likely be valuable at some point.


> However I want to keep the generation code in normal clojure files so they can be shared via regular dependency management (tools.deps). I need to look into babashka more to see what's possible.

Do you mean generated code? Babashka can produce clojure code and write it to a file. I think it would be worthwhile to transition most of the bash code over as it would simplify the languages a user needed to know.

**Comment by jacobobryant** [comment]
> Having the terraform alongside the deployment will likely be valuable at some point.

Could you clarify "Having the terraform alongside the deployment"?

> Do you mean generated code? Babashka can produce clojure code and write it to a file. I think it would be worthwhile to transition most of the bash code over as it would simplify the languages a user needed to know.

No, I mean generation. Specifically, this part, where Biff generates the config files for Terraform and Packer: https://github.com/jacobobryant/biff/blob/2a98365210a17c29230df4e55a193f57aeead339/src/biff/project.clj#L118

To make the Terraform and Packer config reusable and extensible, I like to have the source of truth be EDN and Clojure functions, which can be shared via the regular methods of sharing clojure code (tools.deps in our case). See https://github.com/jacobobryant/biff/blob/master/src/biff/project/infra.clj.

The trouble with that is Clojure's slow startup time. That's why I have Biff generate the Terraform and Packer config when you run `./task dev`. But unfortunately that means if you e.g. change `:biff/host` in `config/main.edn` but don't run `./task dev`, the terraform config will now be out-of-date.

With Babashka, we could generate the config files every time you run a terraform/packer command, so they'd always be up-to-date.

**Comment by jacobobryant** [comment]
Turns out that Babashka takes a classpath argument, so it should work great for Biff. For example:
```shell
$ CLASSPATH=$(clojure -Spath)
$ bb --classpath "$CLASSPATH" --main example.project
```
I'm slightly reticent to add Babashka right away because we don't yet need it _that_ much, and we'd have to add an "Install Babashka" step to Biff's Getting Started instructions (or at least the Deployment instructions). Plus it's added complexity, and it'll take me a little bit of time to restructure things to use it. But sooner or later I think introducing it will make sense.

**Comment by jacobobryant** [comment]
The new project template doesn't manage project files at all since I decided it was more trouble than it was worth.
