### ISSUE TITLE
CI for Biff

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#71]
It'd be nice to have a CI pipeline that has a dedicated digitalocean account (+ api key). Then we could run automated tests for creating and deploying the example project.

**Comment by samhandev** [comment]
Here's an interesting article on using `GitHub actions` to deploy an artefact to Digital Ocean:
https://zemke.io/github-actions-digital-ocean

**Comment by jacobobryant** [comment]
Closing this as I doubt it'll be much of a priority for a long time
