### ISSUE TITLE
apt-get -y upgrade fails in build-image task due to option prompt

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/biff#82]
Thanks for this thoughtful and well-structured starting point to deploying a complete webapp with Clojure(Script) all the way down.

I encountered one problem building the image with the script in `infra/provisioners/20-dependencies` running `apt-get -y upgrade`:

```
    digitalocean: Setting up systemd (245.4-4ubuntu3.4) ...
    digitalocean: Installing new version of config file /etc/dhcp/dhclient-enter-hooks.d/resolved ...
    digitalocean:
    digitalocean: Configuration file '/etc/systemd/resolved.conf'
    digitalocean:  ==> Modified (by you or by a script) since installation.
    digitalocean:  ==> Package distributor has shipped an updated version.
    digitalocean:    What would you like to do about it ?  Your options are:
    digitalocean:     Y or I  : install the package maintainer's version
    digitalocean:     N or O  : keep your currently-installed version
    digitalocean:       D     : show the differences between the versions
    digitalocean:       Z     : start a shell to examine the situation
    digitalocean:  The default action is to keep your current version.
    digitalocean: *** resolved.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package systemd (--configure):
    digitalocean:  end of file on stdin at conffile prompt
    digitalocean: dpkg: dependency problems prevent configuration of netplan.io:
==> digitalocean: No apport report written because the error message indicates its a followup error from a previous failure.
```
As a workaround, I changed the line to `apt-get -y update`. Then after deployment I ran `apt-get -y upgrade` via ssh in order to answer the prompt (choosing the default=N).

At first I tried various noniteractive options in the script to avoid the prompt with no joy.

**Comment by jacobobryant** [comment]
Hey, I ran into that problem recently too actually--I ended up just taking the upgrade command out altogether (https://github.com/jacobobryant/biff/commit/7d025d82ea826fe0a91b9dcb2982cd4e129caa9c). You should upgrade `deps.edn` to include the new version (`:sha "7d025d82ea826fe0a91b9dcb2982cd4e129caa9c"`), otherwise next time you run `./task dev` it'll put the upgrade command back in (though that may not matter much since you've already created the image).

**Comment by jeffp42ker** [comment]
Thanks, I included the new version and successfully ran tasks dev build-image and deploy.
