### ISSUE TITLE
Make github stop thinking this is a javascript project

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/biff#88]
Already set .gitattributes. `github-linguist . --breakdown` already gives me the correct results locally:

```
96.18%  Clojure
3.42%   Shell
0.33%   JavaScript
0.07%   CSS
```

So not sure what the deal is.

**Comment by kloimhardt** [comment]
Not sure if this really helps, but my .gitattributes looks like this:

* linguist-vendored
*.cljs linguist-vendored=false
*.clj linguist-vendored=false

**Comment by jacobobryant** [comment]
That did the trick, thanks.
