### ISSUE TITLE
Cursive, evaluating cljs in nRepl connection

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/biff#93]
This perhaps should have been obvious to me yet I think documenting it might be helpful?

The file watcher re-compiles `/target/resources/public/cljs/app/main.js` whenever .cljs files change. However, at least one user must log into the app before shadow-cljs spins up a CLJS runtime.

Prior to evaluating .cljs code in an nRepl connection on port 7888:
1. log a user into the app
2. eval `(shadow.cljs.devtools.api/repl :app)` to transform the CLJ repl into a CLJS repl.

**Comment by jacobobryant** [comment]
It is a good idea. I'll probably add this soon. Perhaps create another section with development workflow tips, and move some of the current stuff in the getting started section there (e.g. the explanation about evaling and then saving files).

**Comment by jacobobryant** [comment]
No longer needed since new version of Biff doesn't use CLJS.
